<?php
return array(
	'get_autologin_ages'=>'func_autologin_ages.php',
	'captcha_show_image'=>'func_captcha.php',
	'captcha_verify_word'=>'func_captcha.php',
	'duration2friendly_str'=>'func_duration2friendly_str.php',
	'encrypt'=>'func_encryption_with_site8client_keys.php',
	'decrypt'=>'func_encryption_with_site8client_keys.php',
	'get_relative_root_path'=>'func_get_relative_root_path.php',
	'inet_pton2'=>'func_inet.php',
	'inet_ntop2'=>'func_inet.php',
	'my_exit'=>'func_my_exit.php',
	'crypt_random'=>'func_random.php',
	'random_bytes'=>'func_random.php',
	'random_string'=>'func_random.php',
	'shutdown_session'=>'func_shutdown_session.php',
	'verify_hmac'=>'func_site8client_keys_hmac_verifier.php',
	'tr'=>'func_tr.php',
	'utf8_strlen'=>'func_utf8.php',
	'fix_yeh8kaaf'=>'func_yeh8kaaf.php',
);
?>